apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: wordpress
spec:
  snapshotClassName: csi-aws-vsc
  snapshotContentName: snapcontent-c393ad06-000c-11ea-bb60-02c4fcac63ba
---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: wp-snapshot
  namespace: wordpress
spec:
  snapshotClassName: csi-aws-vsc
  snapshotContentName: snapcontent-c3b73263-000c-11ea-bb60-02c4fcac63ba
