apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot
  namespace: wordpress
spec:
  snapshotClassName: csi-aws-vsc
  snapshotContentName: 
---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: wp-snapshot
  namespace: wordpress
spec:
  snapshotClassName: csi-aws-vsc
  snapshotContentName: 
